---
# defaults file for jenkins

java:
  VERSION: "java-1.8.0-openjdk"
  

jenkins:
  repo_URL: "http://pkg.jenkins-ci.org/redhat/jenkins.repo"
  gpg_key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"

docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg
docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present
docker_yum_repo_enable_edge: '0'
docker_yum_repo_enable_test: '0'

# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted
